# Articles

## Resorts World $2.5 billion (Morningstar)

[Resorts World New York City Projects $2.5 Billion to MTA in Next Four Years, Exceeding Budgeted Casino Revenue of $1.8 billion](https://www.morningstar.com/news/pr-newswire/20251031la12512/resorts-world-new-york-city-projects-25-billion-to-mta-in-next-four-years-exceeding-budgeted-casino-revenue-of-18-billion)


- RWNYC could begin operations as early as March 2026 if it is selected by the New York Gaming Facility Location Board ("Board") by December 1, 2025 and the license is issued by the Gaming Commission by December 31, 2025, consistent with the dates the Board has indicated
- upfront license fee of $600 million and $1.9 billion in tax payments to the MTA in the next 4 years, RWNYC will generate $2.5 billion in taxes for the MTA
- MTA's budget from casinos are $500 million in 2026, $500 million in 2027, $600 million in 2028 and $200 million in 2029 for a total of $1.8 billion
- In addition to the MTA, RWNYC will also provide $2 billion to education and $0.5 billion to NYRA in support of the equine industry in New York
- About RWNYC: Resorts World New York City (RWNYC), the only VLT casino-hotel in the five boroughs, has contributed more than $4.5 billion to New York's public education system since opening in 2011. Over the same period, it has provided more than $2 billion to the New York Racing Association, sustaining tens of thousands of jobs across the State's equine industry. RWNYC also fulfils the long-standing objective of transforming the historic Aqueduct Racetrack into the nation's largest gaming destination outside Las Vegas, with approximately 5,500 slot and electronic table games machines.
