# Gaming Facility Location Board

[Landing](https://nycasinos.ny.gov/)

The Board is evaluating each project on the statutory criteria:

-   Economic Activity & Business Development (70%)
-   Local Impact Siting (10%)
-   Workforce Enhancement (10%)
-   Diversity Framework (10%)

> The Board **expects** to make decisions by December 1, 2025, followed by Commission licensure by December 31, 2025. This ensures that New York State will collect the already-booked casino license fee(s) ahead of schedule.\[emphasis added\]

> Minimum Capital Investment: \$500 million.
>
> License Fee: \$500 million
>
> Taxes: Gross gaming revenue will be taxed at a rate to-be-determined by the Commission as part of the competitive application process. An applicant may propose a tax rate on gross gaming revenue as part of its application, so long as the tax rate is at least 25% for slot gross gaming revenue and 10% for gross gaming revenue from all other sources.

>The Board will analyze the revenue impact of each applicant's proposed gaming facility on existing facilities and potential new facilities.
